name: "🚀 deploy CI"
on:
  push:
    branches:
      - demo
      - test
      - dev1
      - dev2
      - dev3
    paths-ignore:
      - 'README*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2
      - name: 🚚 Get node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: 🚚 Get deps
        run: |
          npm install
      - name: 🔨 Build
        run: |
          echo "VUE_APP_LOKAPI_HOST=\"${GITHUB_REF_NAME}.lokavaluto.fr\"" > .env
          echo "VUE_APP_LOKAPI_DB=\"odoo\"" >> .env
          npm run build

      - name: "📂 SFTP Sync files"
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: ${{ github.ref_name }}.lokavaluto.fr
          port: 10322
          user: monujo
          user_private_key: ${{ secrets.sftp_private_key }}
          host_public_key:
          local: ./dist/
          remote: /monujo
          mirror_options: "--verbose"
